// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlnNGjSXUEtSRjp-dFgr9iNCGmvksFIM',
    appId: '1:15335037261:web:2f640e912d1c833ce13f04',
    messagingSenderId: '15335037261',
    projectId: 'fixian2',
    authDomain: 'fixian2.firebaseapp.com',
    databaseURL: 'https://fixian2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixian2.firebasestorage.app',
    measurementId: 'G-759CPRX9JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dna36RMshPIwhjjnFaeVxHh8K0Bcbqs',
    appId: '1:15335037261:android:b3fd32f55d1c724ee13f04',
    messagingSenderId: '15335037261',
    projectId: 'fixian2',
    databaseURL: 'https://fixian2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixian2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5sBk6XJP6ZdEBvH53O6hXV__ZJjG3OQ',
    appId: '1:15335037261:ios:6ba2a286c39a732ee13f04',
    messagingSenderId: '15335037261',
    projectId: 'fixian2',
    databaseURL: 'https://fixian2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixian2.firebasestorage.app',
    iosBundleId: 'com.example.eshebaFixian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl5sBk6XJP6ZdEBvH53O6hXV__ZJjG3OQ',
    appId: '1:15335037261:ios:6ba2a286c39a732ee13f04',
    messagingSenderId: '15335037261',
    projectId: 'fixian2',
    databaseURL: 'https://fixian2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixian2.firebasestorage.app',
    iosBundleId: 'com.example.eshebaFixian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlnNGjSXUEtSRjp-dFgr9iNCGmvksFIM',
    appId: '1:15335037261:web:110153006d9a8059e13f04',
    messagingSenderId: '15335037261',
    projectId: 'fixian2',
    authDomain: 'fixian2.firebaseapp.com',
    databaseURL: 'https://fixian2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixian2.firebasestorage.app',
    measurementId: 'G-HBM3PSPE3Y',
  );
}
